name: "dbt_cta"
version: "1.0.0"
config-version: 2

profile: "dbt_cta"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_cta:
    staging:
      +schema: cta_staging    # Snowflake schema for staging models
      +materialized: view
    marts:
      +schema: cta_marts      # Snowflake schema for mart models
      +materialized: table
